// <auto-generated />
namespace LocadoraGamesCrescer.Infraestrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AceitarValoresNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AceitarValoresNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201706090402151_AceitarValoresNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
